### ISSUE TITLE
Could not connect to development server

### ISSUE THREAD

**Issue by sandrokeil** [pinfake/android-react-native#1]
Hello @pinfake I'm trying the [react native demo app](https://facebook.github.io/react-native/docs/getting-started.html) with your Docker images. The command `adb devices` shows `emulator-5554   device` but the emulator window shows the error *Could not connect to development server*.

I'm a newbie for Android development. Must I configure something in the app? How can I solve this?

**Comment by pinfake** [comment]
I almost forgot everything that has to do with react native development :), I just created the images to help my coleagues having an environment ready to go in the fastest way possible.

But as far as I remember, this could do with running "react-native start" first and before "react-native run-android". I used to run the first command in a separate window (to have its output at sight). I'm using tmux for this on the development environment.

Hope it helps!! :)

**Comment by sandrokeil** [comment]
Thank you, I totally missed the command `react-native start`.

**Comment by pinfake** [comment]
Glad to help!
